export * as fireConfig from './firebase.config'
export {collections} from './collections.config'
export {brandingConfig} from './branding.config'
export {basePath, dashboardPath, loginRedirect, startingPath} from './routes.config'
export {adonisConfig, adonisImagePath} from './adonis.config'
